#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# add map to guest option
CONF=/etc/samba/smb.conf
sed -i "s|guest account = .*|&\n    map to guest = bad user|" $CONF

# change shared folder options to allow guest to access
sed -i "s|[storage]|[storage]\n    guest ok = yes|" $CONF

